// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sonnberg.Persistance;

namespace Sonnberg.Persistance.Migrations
{
    [DbContext(typeof(SonnbergDbContext))]
    partial class SonnbergDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("SonnPropertySonnPropertyTag", b =>
                {
                    b.Property<int>("PropertiesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PropertiesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("SonnPropertySonnPropertyTag");
                });

            modelBuilder.Entity("Sonnberg.Persistance.Entities.SonnLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SonnLocation");
                });

            modelBuilder.Entity("Sonnberg.Persistance.Entities.SonnProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Sonnberg.Persistance.Entities.SonnPropertyTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SonnPropertyTag");
                });

            modelBuilder.Entity("Sonnberg.Persistance.Entities.SonnSuite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("Suites");
                });

            modelBuilder.Entity("Sonnberg.Persistance.Entities.SonnUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SonnPropertySonnPropertyTag", b =>
                {
                    b.HasOne("Sonnberg.Persistance.Entities.SonnProperty", null)
                        .WithMany()
                        .HasForeignKey("PropertiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sonnberg.Persistance.Entities.SonnPropertyTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sonnberg.Persistance.Entities.SonnProperty", b =>
                {
                    b.HasOne("Sonnberg.Persistance.Entities.SonnLocation", "Location")
                        .WithMany("Properties")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Sonnberg.Persistance.Entities.SonnSuite", b =>
                {
                    b.HasOne("Sonnberg.Persistance.Entities.SonnProperty", "Property")
                        .WithMany("Suites")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Sonnberg.Persistance.Entities.SonnLocation", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("Sonnberg.Persistance.Entities.SonnProperty", b =>
                {
                    b.Navigation("Suites");
                });
#pragma warning restore 612, 618
        }
    }
}
